### ISSUE TITLE
flecsale can't be used as a cinch subproject

### ISSUE THREAD

**Issue by cmsquared** [losalamos/flecsale#15]
flecsale has its own cmake files in flecsale/cmake 

Following cinch's behavior, this path is added to `CMAKE_MODULE_PATH` in flecsale/config/project.cmake, but it is added as `${CMAKE_SOURCE_DIR}/cmake`.  This works fine when flecsale is standalone, but if it is included as a subproject (via `cinch_add_subproject`), then the correct path isn't added.

The fix is to change it to `${CMAKE_CURRENT_SOURCE_DIR}`, which builds correctly as a subproject.  

I would have issued a pull request, but I didn't want to fork all the damn dependencies in flecsi that use relative paths...

**Comment by charest** [comment]
You can make a branch and submit a pull request, you wont need to fork dependencies.

**Comment by cmsquared** [comment]
I didn't know I had write permission...

**Comment by charest** [comment]
If you are in the losalamos group you should be able to... I think

**Comment by cmsquared** [comment]
Cloning still wants losalamos/google/googletest for gtest inside cinch...  I know I can get around it, but the relative paths really chap my ass.

**Comment by cmsquared** [comment]
Actually....it was complaining about losalamos/google/googletest because of the older version of git on the system...got it now

**Comment by cmsquared** [comment]
Nope, I don't have permissions:

```{sh}
cmalone@barugon:~/code/flecsale$ git push -u origin subproject_fix
ERROR: Permission to losalamos/flecsale.git denied to cmsquared.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by junghans** [comment]
@cmsquared: I gave you write to the repo.
@charest: You might want to lock down master, so that only you can push to it.

And yes, ancient versions of git have a bug in parsing "../..", but darwin has a git module, which works.
